name: Build and Package Java Project with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adoptopenjdk'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Package with Maven
      run: mvn package

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app-jar
        path: target/jb-hello-world-maven-0.2.0.jar
